export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const OPEN_EMAIL_MODAL = "OPEN_EMAIL_MODAL";
export const CLOSE_EMAIL_MODAL = "CLOSE_EMAIL_MODAL";
export const OPEN_HOSTING_MODAL = "OPEN_HOSTING_MODAL";
export const CLOSE_HOSTING_MODAL = "CLOSE_HOSTING_MODAL";
export const CLOSE_ADD_POST = "CLOSE_ADD_POST";
export const ADD_POST = "ADD_POST";
export const GET_USER_POSTS = "GET_USER_POSTS";
export const GET_POSTS_BY_DESTINATION = "GET_POSTS_BY_DESTINATION";
export const GET_POSTS_BY_CITY = "GET_POSTS_BY_CITY";

export const GET_ADMIN_PROFILE = "GET_ADMIN_PROFILE";
export const GET_USERS_LIST = "GET_USERS_LIST";
